version: '3'

# This docker-compose is for developer convenience, not for running in production.

services:

  # For running the python consumers
  web:
    image: searchapi2:${TAG:-dev}
    build:
      context: .
    depends_on:
      - elasticsearch
    volumes:
      - ${PWD}:/app
    ports:
      - "127.0.0.1:5000:5000"
    environment:
      - DEVELOPMENT=1
      - PYTHONUNBUFFERED=true
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - WORKERS=2

  elasticsearch:
    image: elasticsearch:7.8.0
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "127.0.0.1:9200:9200"
      - "127.0.0.1:9300:9300"
