#!/bin/sh
set -e
set -o xtrace

cleanup () {
  echo "Stopping container.."
  docker stop $(docker ps -aq)
}

cleanup
trap cleanup EXIT
path=${@:-"tests/integration"}
export PYTHONPATH=.
poetry run pytest -vv -s $path
