#!/bin/sh

set -e
set -o xtrace

export PYTHONPATH=.
export WORKSPACE_URL="http://localhost:5555/ws"

path=${@:-"tests/unit"}

poetry run flake8
poetry run mypy --ignore-missing-imports src/**/*.py
poetry run bandit -r src

echo "Running tests in $path"
poetry run pytest -vv --cov=./src --cov-report=xml $path
poetry run coverage html
poetry run coverage report
