name: Build, Test, Push for Development Scenarios and Release

on:
  push:
    branches: [ develop, "fix-*", "feature-*" ]
  release:
    types: [published]

jobs:
  docker_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
      - name: Check out GitHub Repo
        uses: actions/checkout@v2

      # Imports many useful environment variables
      - uses: FranzDiebold/github-env-vars-action@v2

      # Unit (ish) tests
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Pip installation
        run: python -m pip install --upgrade pip poetry
      - name: Poetry installation
        run: poetry install
      - name: Create test image
        env:
          TAG: ${{ env.CI_ACTION_REF_NAME }}
        run: docker-compose build
      - name: Run tests
        run: scripts/run_tests
      - name: Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          fail_ci_if_error: true

      # Build and Push (if we get here)
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry (GHCR)
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          pull: true
          push: true
          build-args: |
            BUILD_CONFIG=ci
            BUILD_DATE=${{ steps.date.outputs.date }}
            VCS_REF=${{ github.sha }}
            BRANCH=${{ github.ref }}
            TAG=${{ github.ref }}
          tags: ghcr.io/${{ github.repository_owner }}/searchapi2:${{ env.CI_ACTION_REF_NAME }}
